/**
 * Backward compatibility exports
 * Use modular imports in new code
 */

import { API_BASE_URL, USER_AGENT, AXIOS_TIMEOUT_MS } from './api.js'
import { buildProxyUrl } from './proxy.js'
import { OAUTH_TOKEN_URL, OAUTH_AUTHORIZE_URL, USER_INFO_URL, OAUTH_SUCCESS_REDIRECT, OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, DEFAULT_OAUTH_PORT_START, DEFAULT_OAUTH_PORT_RANGE } from './oauth.js'

/**
 * @deprecated Use individual constants from modular imports
 */
export const IFLOW_CONSTANTS = {
  BASE_URL: API_BASE_URL,
  PROXY_URL: buildProxyUrl(),
  OAUTH_TOKEN_URL,
  OAUTH_AUTHORIZE_URL,
  USER_INFO_URL,
  SUCCESS_REDIRECT: OAUTH_SUCCESS_REDIRECT,
  CLIENT_ID: OAUTH_CLIENT_ID,
  CLIENT_SECRET: OAUTH_CLIENT_SECRET,
  AXIOS_TIMEOUT: AXIOS_TIMEOUT_MS,
  USER_AGENT,
  CALLBACK_PORT_START: DEFAULT_OAUTH_PORT_START,
  CALLBACK_PORT_RANGE: DEFAULT_OAUTH_PORT_RANGE
}
